### PR TITLE
fix: add aliases param to option

### PR DESCRIPTION
**Pull request by MoartMedia**
**Please describe the changes this PR makes and why it should be merged:**

Missing alias param Options
In result alias init is not working.
so fix it.

**Status**

- [x] Code changes have been tested.

**Semantic versioning classification:**

- [ ] This PR includes new feature, methods or parameters
  - [ ] This PR includes breaking changes (feature, methods, parameters removed or renamed)
- [ ] This PR **only** includes non-code(typo, documentation etc.) changes

### CODE REVIEW

**Comment by zero734kr** [comment]
미리 고생하시라고 문안 왔습니다

**Comment by zero734kr** [comment]
죄송하지만 전 먼저 튈게요 (자러감)

**Review by wonderlandpark — CHANGES_REQUESTED** [review]
Could you change the PR description in English?

**Comment by MoartMedia** [comment]
> Could you change the PR description in English?

Done

**Review by wonderlandpark — APPROVED** [review]

**Comment by wonderlandpark** [comment]
Thanks for your contribution.

**Comment by zero734kr** [comment]
뭔가 억울한데

**Comment by wonderlandpark** [comment]
@zero734kr your comment was hidden due to off-topic.

**Pull request merged**
